name: cypress e2e test
on:
  pull_request:
    types: [opened, reopened]
# defaults:
  # run:
  #   working-directory: ./frontend
jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:  
      - name: Checkout repository
      uses: actions/checkout@v2

      - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Cypress가 지원하는 Node.js 버전을 사용합니다.

      - name: Install node modules
        run: npm install


      - name: Run Cypress test
        run: npm run cypress:run